# -*- coding: utf-8 -*-
"""sentence-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DPrM2ihgMA61GuhS_0MsG7Ocq_8vAEP
"""

!pip install nltk textblob vaderSentiment --quiet
!pip install detoxify
from detoxify import Detoxify
toxicity_model = Detoxify('original')
import nltk
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Download NLTK resources
nltk.download('punkt')
nltk.download('vader_lexicon')

# VADER Sentiment Analyzer
analyzer = SentimentIntensityAnalyzer()

def analyze_sentiment(text):
    # Using TextBlob for polarity
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity  # -1 to +1

    # Using VADER for sentiment scores
    vs = analyzer.polarity_scores(text)
    vader_compound = vs['compound']

    # Determine overall sentiment
    if vader_compound >= 0.05:
        sentiment = "Positive"
    elif vader_compound <= -0.05:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"

    # Determine emotion hints (basic lexicon-based)
    emotion = []
    positive_words = ["happy","joy","love","good","excellent","great","awesome","fantastic"]
    negative_words = ["sad","angry","bad","terrible","hate","worst","poor","horrible"]

    for word in positive_words:
        if word in text.lower():
            emotion.append("Joy")
    for word in negative_words:
        if word in text.lower():
            emotion.append("Anger/Sadness")

    if not emotion:
        emotion.append("Neutral/Mixed")
    # Toxicity detection
    toxicity = toxicity_model.predict(text)

    return {
        "Text": text,
        "Sentiment": sentiment,
        "Polarity": round(polarity, 3),
        "Toxicity Score": round(toxicity['toxicity'],3),
        "VADER Compound": vader_compound,
        "Emotion": emotion
    }

while True:
    user_input = input("Enter text to analyze (or type 'exit' to quit): ")
    if user_input.lower() == 'exit':
        print("Exiting Sentiment Analyzer. Bye!")
        break
    result = analyze_sentiment(user_input)
    print("\n📊 Sentiment Analysis Result:")
    print(f"Text: {result['Text']}")
    print(f"Sentiment: {result['Sentiment']}")
    print(f"Polarity (TextBlob): {result['Polarity']}")
    print(f"VADER Compound: {result['VADER Compound']}")
    print(f"Detected Emotion: {', '.join(result['Emotion'])}\n")